version: '3.8'

services:
  pgsqldb:
    image: postgres:16.3
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"
      POSTGRES_DB: "${DB_NAME}"
    ports:
      - 5432:5432
    volumes:
      - pgsqldata:/var/lib/postgresql/data
volumes:
  node_modules:
  pgsqldata:
